site_name: Regenerative Agriculture
theme:
  name: material
  palette:
    primary: green
extra:
  analytics:
    provider: google
    property: G-21RC337R1E
markdown_extensions:
  - footnotes
  - tables
  - attr_list
extra_css:
  - extra.css
