site_name: Regenerative Agriculture Community
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.svg
  palette:
    primary: green
extra:
  analytics:
    provider: google
    property: G-21RC337R1E
markdown_extensions:
  - footnotes
  - tables
  - attr_list
extra_css:
  - assets/extra.css
